# Generated by Django 4.2 on 2024-01-26 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_name', models.CharField(max_length=256)),
                ('items_desc', models.CharField(max_length=256)),
                ('items_price', models.FloatField()),
            ],
        ),
    ]
